name: Tests on Pull Request

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          pip install pytest
      - name: Run tests
        run: |
          pytest